spring.application.name=KingsMarket

# ----------------------------------------
# CONFIGURAÇÃO DO BANCO DE DADOS (ORACLE FIAP)
# ----------------------------------------
# URL montada com: jdbc:oracle:thin:@<Hostname>:<Port>:<SID>
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm562005
spring.datasource.password=311005
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ----------------------------------------
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ----------------------------------------
# Cria e atualiza as tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect